#!/usr/bin/env bash
# direnv customization

# Initializes per-project postgres
layout_postgres() {
  PGDATA="$(direnv_layout_dir)/postgres"
  PGHOST="$PGDATA"
	export PGDATA PGHOST

	if [[ ! -d "$PGDATA" ]]; then
    log_status "Initializing postgres for this project..."
		initdb
		cat >> "$PGDATA/postgresql.conf" <<-EOF
			listen_addresses = ''
			unix_socket_directories = '$PGHOST'
		EOF
        echo "CREATE DATABASE $USER;" | postgres --single -E postgres
	fi
}
