redactions = ["*_KEY", "*_TOKEN", "*_SECRET", "*_PASSWORD"]

[tools]
"cargo:bottom" = "latest"
"cargo:fd-find" = "latest"
"cargo:hyperfine" = "latest"
"cargo:nu" = "latest"
"cargo:skim" = "latest"
"cargo:toml-cli" = "latest"
"cargo:zellij" = "latest"
"go:github.com/fullstorydev/grpcurl/cmd/grpcurl" = "latest"
go = { version = "1.26.0", postinstall = "mise install_go_tools" }
gum = "latest"
jq = "latest"
just = "latest"
node = "25.6.1"
python = "3.14.3"
ruby = "4.0.1"
rust = "stable"
shellcheck = "latest"
shfmt = "latest"
tree-sitter = "latest"
uv = "latest"
yq = "latest"
claude = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
pin = true
python.uv_venv_auto = true

[env]
MISE_ENV = "development"
MACOSX_DEPLOYMENT_TARGET = "26.4"  # bump after major macOS upgrades (sw_vers -productVersion)

[tasks.install_go_tools]
description = "Install Go Tools Specific to a Version of Go"
run = [
	"go install github.com/go-delve/delve/cmd/dlv@latest",
	"go install golang.org/x/tools/gopls@latest",
]
