redactions = ["*_KEY", "*_TOKEN", "*_SECRET", "*_PASSWORD"]

[tools]
"aqua:anthropics/claude-code" = "2.1.126"
"aqua:astral-sh/uv" = "0.11.8"
"aqua:casey/just" = "1.50.0"
"aqua:charmbracelet/gum" = "0.17.0"
"aqua:cli/cli" = "2.92.0"
"aqua:fullstorydev/grpcurl" = "1.9.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:koalaman/shellcheck" = "0.11.0"
"aqua:mikefarah/yq" = "4.53.2"
"aqua:neovim/neovim" = "0.12.2"
"aqua:sharkdp/fd" = "10.4.2"
"aqua:zellij-org/zellij" = "0.44.1"
"pipx:httpie" = "3.2.4"
go = { version = "1.26.2", postinstall = "mise install_go_tools" }
node = "25.9.0"
python = "3.14.4"

[settings]
experimental = true
pin = true
python.uv_venv_auto = true

[env]
MISE_ENV = "development"
MACOSX_DEPLOYMENT_TARGET = "26.4" # bump after major macOS upgrades (sw_vers -productVersion)

[tasks.install_go_tools]
description = "Install Go Tools Specific to a Version of Go"
run = [
  "go install github.com/go-delve/delve/cmd/dlv@latest",
  "go install golang.org/x/tools/gopls@latest",
]
